title: Vanilla OS Documentation
author: Vanilla OS Contributors
email: send@mirko.pm

assets: /documentation/assets
uploads: /documentation/uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
